project_id = "vixczylcdviqivlziovw"

[functions.step-tts]
verify_jwt = false

[functions.generate-voice-audio]
verify_jwt = false

[functions.generate-tts-audio]
verify_jwt = false

[functions.clone-voice]
verify_jwt = false
